language: java
jdk:
 - openjdk11

branches:
 only:
  - master

before_install:
 - pip install --user codecov
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

script:
 - ng -v
 - ng lint
 - npm run test-coverage
 - ng build --configuration production --base-href "/spotitube/"
 - curl "http://ci.icaprojecten.nl/jenkins/buildByToken/build?job=OOSE-DEA-Spotitube-client&token=$JENKINS_TOKEN"

after_success:
 npm run coveralls
 - codecov --file coverage/lcov.info --disable search

deploy:
 provider: pages
 local-dir: dist
 skip-cleanup: true
 github-token: $GH_TOKEN
 keep-history: false
 on:
  branch: master